# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 19:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('order', models.PositiveIntegerField(verbose_name='ordem')),
                ('done', models.BooleanField(default=False, verbose_name='feita')),
            ],
        ),
    ]
